### ISSUE TITLE
KubernetesCluster link doesn't contain 'zones'

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1205]
https://github.com/GoogleCloudPlatform/forseti-security/blob/10e21c31a4e794cb61d6434cc5dda910433b2082/google/cloud/forseti/services/inventory/base/resources.py#L805-L811

return self_link_parts[self_link_parts.index('zones')+1]

but in some cases self_link_parts doesn't contain 'zones'
e.g. [u'https:', u'', u'container.googleapis.com', u'v1', u'projects', u'gke-accel-demo', u'locations', u'europe-west1', u'clusters', u'accelerate-eu']

**Comment by ahoying** [comment]
This is more complicated to fix than I originally assumed, as it has to be plumbed all the way through to the base API call to handle clusters in Locations instead of Zones, and that API is part of a new version, v1beta1, of the Kubernetes API.

Details:

class KubernetesCluster needs a new method, locations(), that will return self_link_parts[self_link_parts.index('locations')+1] 

Neither .zone() or .location() should log a warning if they are not found, the log message should be a debug log.

https://github.com/GoogleCloudPlatform/forseti-security/blob/10e21c31a4e794cb61d6434cc5dda910433b2082/google/cloud/forseti/services/inventory/base/resources.py#L770

needs to pass the value of both .zone() and .location() to fetch_container_serviceconfig. One or the other will be an empty string.

https://github.com/GoogleCloudPlatform/forseti-security/blob/10e21c31a4e794cb61d6434cc5dda910433b2082/google/cloud/forseti/services/inventory/base/gcp.py#L439

needs to take either a zone and a location, and pass that on to get_serverconfig().

https://github.com/GoogleCloudPlatform/forseti-security/blob/10e21c31a4e794cb61d6434cc5dda910433b2082/google/cloud/forseti/common/gcp_api/container.py#L154

get_serverconfig needs to take either a zone or optionally a location, and if the zone is set to an empty string and it is passed a location it needs to call self.repository.projects_locations.get_serverconfig().

The projects.locations repository will need to be added. The getServerConfig for projects.locations takes a single name parameter, with the format of the project and location of the server config to get specified in the format 'projects/*/locations/*'. Also complicating this is projects.locations is a v1beta1 API, so a second API version needs to be added to the ContainerRepositoryClient, similar to how the multiple API versions are handled in the ResourceManagerClient.

So in the example above:
cluster = KubernetesCluster(...)
cluster.zone() returns ''
cluster.location() returns 'europe-west1'
cluster.get_kubernetes_service_config() calls:
  client.fetch_container_serviceconfig(self.parent().key(), zone=self.zone(), location=self.location())
That calls self.container.get_serverconfig(projectid, zone=zone, location=location)
That calls self.repository.project_locations.get_serverconfig(projectid, location)
That transforms projectid and location into 'projects/{}/locations/{}'.format(projectid, location) and calls the API, https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations/getServerConfig, with that value set as the name parameter.
