### ISSUE TITLE
Folder support

### ISSUE THREAD

**Issue by carise** [GoogleCloudPlatform/forseti-security#142]
We are interfacing with customers who have folders enabled.

- [x] When pulling the project list into inventory, make sure to look in folders for other projects.
- [x] Scanner should also take folders into account (e.g. making rules that apply to folders as well as respecting rule inheritance)

**Comment by ahoying** [comment]
https://github.com/GoogleCloudPlatform/forseti-security/blob/master/google/cloud/security/common/gcp_api/cloud_resource_manager.py#L86 needs to change to support folders. This filter will not return any projects under folders, which will have a parent type of folder, and a parent id of the folder id.

Suggested work around:

Don't set a filter on projects.list(), rather for each returned project check the project parent and if type is organization, validate the org id. If it is folder, then call crm.projects().getAncestry(projectId=project_id, body={}) to get the full ancestry and verify the folder is a child of the organization id. The full ancestry can be added to the project data in the SQL database as well to support Scanner.

I also suggest making organization_id an optional argument, and returning all results if it is not set, so that projects in the null org are also returned, if the service account has visibility to them.

**Comment by carise** [comment]
Yes. We definitely need to do this.

I have a small prototype that will list projects under an organization as well as inside the org's folders. Don't know if this another approach to consider though.

https://github.com/carise/gcp-utils/blob/master/resource-manager/project_list.py

**Comment by carise** [comment]
Finally finished this with #447
