### ISSUE TITLE
Update the deployment template generation to pull from the version from which it was built

### ISSUE THREAD

**Issue by mirons-google** [GoogleCloudPlatform/forseti-security#1430]
When we generate the deployment template (startup script) included we should pull from the version for which the deployment template was generated.

Please also confirm that the startup script should have git checkout for all use-cases.

**Comment by joecheuk** [comment]
In non-advanced installation mode, we will infer the Forseti branch to installed to be the installer branch.

https://github.com/GoogleCloudPlatform/forseti-security/blob/1c053b6640da220ca42627418565a3a1a6811422/setup/gcp/installer/util/utils.py#L236

In deployment template, we will always pull from the branch installed because we have the branch information stored inside.

**Comment by joecheuk** [comment]
Hey @mirons-google , can this issue be closed or you still need more information?
