### ISSUE TITLE
Provide a mechanism to easily disable the inventory notification emails.

### ISSUE THREAD

**Issue by lukwam** [GoogleCloudPlatform/forseti-security#170]
I temporarily changed the sendgrid token to '' make it stop emailing me every hour with the inventory snapshot notification, but that isn't very elegant because it generates an authentication error in the log and i have to apply the change I pull down a new version of the repo.

It would be nice if there was an easy way to decide if you want to receive the inventory notifications or not.

**Comment by blueandgold** [comment]
Hi Lukas,

This has recently been addressed in this PR
<https://github.com/GoogleCloudPlatform/forseti-security/pull/147>, and
included in the new 1.0.1 release.

So, instead of the sendgrid token, you can comment out (or remove) the
email_recipient in the deployment yaml file.  Then, the email notification
will not be sent. (documentation
<https://github.com/GoogleCloudPlatform/forseti-security/blob/f4f40c6b231483066408c7ebbca9ce620efcc9aa/docs/prerequisites/README.md#L81>
)

Note that doing so will apply to both the inventory and policy scanner
emails.  Please let us know how this works for you.

Thanks.

**Comment by carise** [comment]
Closing this as I think it's more or less resolved. :)
