### ISSUE TITLE
HTML-proofer is unable to verify external link

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1881]
The link is working, but the html-proofer does not agree.  Re-ran the build several times, but did not help.

https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/414909672?utm_source=github_status&utm_medium=notification

![image](https://user-images.githubusercontent.com/6977544/44039865-ebecd55e-9ece-11e8-9e60-d1266f6e8609.png)

This is the link:
https://www.gcppodcast.com/post/episode-120-forseti-with-nenad-stojanovski-and-andrew-hoying/

**Comment by EricBeach** [comment]
See https://github.com/GoogleCloudPlatform/forseti-security/pull/1877#issuecomment-412294339

**Comment by EricBeach** [comment]
Loading gcppodcast.com using Firefox from a GCP machine results in the same underlying certificate error. Loading via Chrome succeeds, presumably because gcppodcast.com is signed by ``CN=GTS CA 1O1 O=Google Trust Services`` which is a part of the Google PKI (see https://pki.goog/) infrastructure and presumably Chrome trusts Google PKI at the browser level before even looking down into the operating system.

I will reach out to some folks in GCP to figure out why our own images do not trust certs for our own website.

![screenshot from 2018-08-13 13-13-20](https://user-images.githubusercontent.com/3344366/44046883-cf1a1afa-9efa-11e8-9386-545619244907.png)

**Comment by EricBeach** [comment]
I talked to the appropriate party inside Google and this issue should now be resolved. The root issue was not with Forseti.

**Comment by EricBeach** [comment]
Confirmed build now passes on Travis https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/415501121

**Comment by blueandgold** [comment]
Awesome, thanks for chasing this down!
