### ISSUE TITLE
Extra Messages when Using the CLI

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2164]
Testing 2.7.0 pre-release.  When running the CLI on both server and client VMs, there are lots of extra messages.

![image](https://user-images.githubusercontent.com/6977544/47827067-dd916300-dd38-11e8-98b8-b62822c3bc10.png)

**Comment by ocervell** [comment]
@blueandgold We should be able to disable OpenCensus logger here, to not show extraneous messages we don't need. 

The 'lag' you're observing corresponds to sending traces to the tracing service after a gRPC call (Inventory.list in this case). It shouldn't much more than ~200/300ms, corresponding to Stackdriver Trace API latency. 

Note that the emission of traces doesn't happen in the main thread but in a background thread, so in any case it doesn't slow / block execution of the gRPC services themselves.

**Comment by ocervell** [comment]
To reduce the CLI lag, we can also:

- **disable client-side tracing**, which would eliminate the client-side lag, but we would lose client --> server latency tracing

- **lower the sampling rate**, so that only a percentage of all gRPC calls are traced (currently 100%). This would lower the number of traces to be sent, but make it more difficult to trace one particular gRPC call since it might not show up in the console.

The first bullet can already be done by uninstalling OpenCensus on the client VM.
The second bullet can be done by making the sampling rate configurable.
