### ISSUE TITLE
Bucket ACL Scan Not Working

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2540]
Tag 2.10.0

File bucket _rules.yaml is included in the codebase though it appears to be non functional.

I checked the server config to ensure rule is turned on

- name: bucket_acl
          enabled: true

bucket rules doesn't trigger alerts when expected

**Comment by Red-Five** [comment]
On further investigation I think the bucket rules is only against ACL and the IAM rules is for IAM.

So possibly close this issue; though it is a bit confusing for users.

**Comment by katze120** [comment]
Bucket ACL Scan has been working for me for legacy ACLs until version 2.8.0
I'm able to reproduce the same issue from version 2.9.0, and believe the reason is as follows:

1. In 2.9.0 Forseti inventory starts pulling bucket info from CAI: https://github.com/GoogleCloudPlatform/forseti-security/releases/tag/v2.9.0
2. CAI output has empty "acl" information in "data" session. 
After forseti model is created, we can also see empty "acl" information, this can be verified by running "select data from <unique_id>_resources where type="bucket";" in forseti_security database.
I also troubleshooted by adding debugging lines in ./google/cloud/forseti/scanner/scanners/bucket_rules_scanner.py , bucket_acls from "buckets_acls = self._retrieve()" is empty 
3. One possible way to fix this is to add legacy storage roles into "storage_iam_roles" frozenset of google/cloud/forseti/scanner/scanners/iam_rules_scanner.py, I tried this based on forseti 2.10.0 code and was able to get findings in legacy bucket ACLs in "iam" violations; in this way we no longer need to use the bucket acl rule.

Let's see whether there are better suggestions to fix this.

**Comment by ahoying** [comment]
Use of the iam scanner is the preferred approach going forward. The documentation needs to be updated to show this change. @hshin-g - can you look at updating the docs for the next release?

**Comment by Red-Five** [comment]
@ahoying The IAM scanner does not (currently) appear to pick up the pure ACL roles set via gsutil acl command.

In the case gsutil acl is used, there is only an ACL entry and that is not flagged.

I think (to be verified) if the IAM legacy roles are used then a corresponding ACL entry is added in addition to the IAM entry and the IAM rule reports only on the IAM portion of the settings.

**Comment by ahoying** [comment]
The IAM data is a direct replica of the ACL data. ACLs are stored as IAM policies on the backend, and that is the data that is sent when using CAI. Both IAM and ACL data are stored in the inventory, but it looks like the scanner is looking at the wrong place.

The importer should be loading in the gcs_policy as it's own resource (Like https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/forseti/services/model/importer/importer.py#L271 but with fetch_gcs_policy set to True).

Then the scanner should be updated to read that resource directly.

That will fix the ACL scanner issue while still allowing you to have a separate policy for the IAM scanner.

**Comment by ahoying** [comment]
I'm going to take this issue and work on a fix as documented above.
