### ISSUE TITLE
CAI enabled vs. disabled IAP violation discrepancy

### ISSUE THREAD

**Issue by hshin-g** [GoogleCloudPlatform/forseti-security#2548]
The IAP scanner retrieves violations when CAI is disabled, while no violations are found when CAI is enabled.

**Comment by ahoying** [comment]
Root cause: conversion between json and protobuf and back to python dict was causing integer values to change to float values. This threw off the comparison logic in the IAP scanner.

The fix is to modify the CAI temporary database to store the raw json instead of converting to protobuf first.

This has the added advantage of fixing certain IAM policies that could not convert to protobuf correctly.
