### ISSUE TITLE
ke_scanner length(nodePools) Issue

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/forseti-security#2665]
@rvandegrift 
If nodePools is missing from Cluster json data; length(nodePools) in JMSEPath rules will crash the scanner, halting further evaluation of its rules.

**Comment by rvandegrift** [comment]
You can specify a fallback value with JMESPath's Or Expressions.  For instance, this expression takes the value of `nodePools` if it is defined, and an empty list otherwise:
```
nodePools || `[]`
```

The KE scanner shouldn't misbehave in this scenario.  There's a bug at https://github.com/GoogleCloudPlatform/forseti-security/blob/fe8d79f1b09e41b4341ab4558374c0e51030259c/google/cloud/forseti/scanner/audit/ke_rules_engine.py#L317 - this should catch `JMESPathTypeError` and put something in the logs
