### ISSUE TITLE
Default setup wizard version to the current release version

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#465]
Currently, the setup wizard has a flag for users to specify which release or branch to use.
https://github.com/GoogleCloudPlatform/forseti-security/blob/explain-pre-release/scripts/gcp_setup/setup_forseti.py

But if users were to follow the setup documentation, this flag is not mentioned, would not be used, and would then just default to point to master, which can cause the setup to bork as master's code base moves ahead and out of sync with the DM templates.

http://forsetisecurity.org/docs/quickstarts/forseti-security/index.html
https://github.com/GoogleCloudPlatform/forseti-security/blob/master/scripts/gcp_setup/environment/gcloud_env.py#L784

Some options:
1: The documentation can be updated to tell users how to use this flag.
2: The setup wizard can prompt user to enter this.
3: Track the version in the forseti_conf.yaml, which will be updated before each release.
3: When release is created, the packaged setup wizard is pointed to the release.

**Comment by carise** [comment]
I'll take this in 2 steps.

1. Update documentation, first.
2. Default the setup wizard to the release version, which involves the following:
   * Fix the setup.py version import to use execfile instead of importing the version from g.c.security
   * Import that version into the setup wizard. I prefer not to have to update so many places to track the release version. (Right now we update deploy-forseti.yaml.sample as well as g.c.s.__init__; I would like to keep it that way.)

I will only address step 1 in #478 and in a separate PR for documentation.

**Comment by blueandgold** [comment]
Since step 1, then step 2 is not needed as we have to moved to the git release flow, where master is the latest release version.  So, no changes would be needed.
