### ISSUE TITLE
repr instead of json.dumps in instance network interface scanner

### ISSUE THREAD

**Issue by gbrindisi** [GoogleCloudPlatform/forseti-security#665]
Hello,
looks like in `dev` the network_interface_scanner is using `repr` insted of `json.dumps`to save the `raw_data` (within `violation_data`): https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/security/scanner/audit/instance_network_interface_rules_engine.py#L246

But according to a previous PR this should not be the case: https://github.com/GoogleCloudPlatform/forseti-security/pull/639/files#diff-52fba022d2d7ec64b70d687d13803eb6R247

We missed a commit perhaps?
Can you look into this?

**Comment by blueandgold** [comment]
Hi Gianluca,

I looked at the [history of this file](https://github.com/GoogleCloudPlatform/forseti-security/commits/dev/google/cloud/security/scanner/audit/instance_network_interface_rules_engine.py).

It looks like there was a [bad revert in PR #641](https://github.com/GoogleCloudPlatform/forseti-security/pull/641/files), so that Andrew can do some [improvement in PR #642](https://github.com/GoogleCloudPlatform/forseti-security/pull/642/files) .

I will send out a PR to fix this.
