### ISSUE TITLE
Scanner for rotation of service account keys

### ISSUE THREAD

**Issue by radkomateusz** [GoogleCloudPlatform/forseti-security#790]
Forseti currently has an information about service account keys in inventory. 

It will be nice to have a scanner for scanning when keys are generated and reporting keys which exceed fixed timeout. 

In our use case, we want to enforce users to rotating their service account keys every few months/weeks etc.

**Comment by BrainPeel** [comment]
A large customer of ours is also looking to Forseti to enforce the timely rotation of keys. +1

**Comment by blueandgold** [comment]
@rgmenon is currently working on this.

**Comment by rgmenon** [comment]
See PR https://github.com/GoogleCloudPlatform/forseti-security/pull/1630
1. You set the maximum key age you want to allow in the new service_account_key_rules.yaml, max_age parameter
2. Here's an  example of how the violations will look. To be able to more easily find the offending key in the GCP console, I also added the service account name (display_name in the API response) and id (email) to the violation_data (in addition to the key_id of course):
mysql> select * from violations where violation_type = 'SERVICE_ACCOUNT_KEY_VIOLATION';
+----+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------+------------+--------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| id | created_at_datetime | full_name                                                                                                                                                 | resource_data                                                                                                                                                                                                                                                                                                                                                     | resource_id                                                                | resource_type      | rule_index | rule_name                                              | scanner_index_id | violation_data                                                                                                                                                                                                                                                                                                                                                                                                   | violation_hash                                                                                                                   | violation_type                |
+----+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------+------------+--------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 32 | 2018-06-02 23:02:35 | organization/xxxxxxxxxxxx/project/forseti-security-test/serviceaccount/107143282859021501353/serviceaccount_key/6e1e955410cecdb09083179d409bf8e9b69afe95/ | {'key_id': '6e1e955410cecdb09083179d409bf8e9b69afe95', 'key_algorithm': u'KEY_ALG_RSA_2048', 'valid_after_time': u'2017-11-04T17:23:06Z', 'valid_before_time': u'2027-11-02T17:23:06Z', 'full_name': 'organization/xxxxxxxxxxxx/project/forseti-security-test/serviceaccount/107143282859021501353/serviceaccount_key/6e1e955410cecdb09083179d409bf8e9b69afe95/'} | yyyyyyyyyy-yyyyyyyy-editor@forseti-security-test.iam.gserviceaccount.com   | serviceaccount_key |          0 | Service account keys not rotated (older than 100 days) | 1527980550787881 | {"key_created_time": "2017-11-04T17:23:06Z", "violation_reason": "Key ID 6e1e955410cecdb09083179d409bf8e9b69afe95 not rotated since 2017-11-04T17:23:06Z.", "service_account_name": "yyyyyyyyyy-yyyyyyyy-editor", "service_account_id": "yyyyyyyyyy-yyyyyyyy-editor@forseti-security-test.iam.gserviceaccount.com", "key_id": "6e1e955410cecdb09083179d409bf8e9b69afe95", "project_id": "forseti-security-test"} | f050a15fe3f202bf0d954b1ba276b6033ff2af97bee60d42a81dd9760b0f84c0429517c0820f46d2cabd5b51175683e34d9a722daf23542b94c49196eb014ab0 | SERVICE_ACCOUNT_KEY_VIOLATION |

**Comment by blueandgold** [comment]
Thank you for closing this out Ramesh!
