### ISSUE TITLE
Add Column For Organization Root to InventoryIndex

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#992]
This will serve to uniquely identify data from different forseti instances (when different forseti instances are used to crawl different organizations, and then the data from the instances are joined).

**Comment by jiyunyao** [comment]
Changing id to use timestamp can solve the issue of collision when merging multiple database and it is easy to sort. The stamp generated here is like:'2018-01-30T04:30:34.16326'. 2 digits more than ms. It will be very very unlikely to cause collision using cron job.
In addition to that. My opinion is that a new column for root id is unnecessary since it can be acquired without that column.

**Comment by jiyunyao** [comment]
Compare this branch with the 2.0-dev, one can easily learn how to get inventory root_id. A method in inventory storage is provided to query this.
